config/routes.rb
Rails.application.routes.draw do
  resources :blog_posts
  devise_for :users
  root to: "blog_posts#index" 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord

  belongs_to :user

  validates :title, presence: true
  validates :content, presence: true
  validates :image, presence: true

  before_validation :fetch_image, no: :create
  before_update :fetch_image
  private

  def fetch_image
    # return if image.present?

    photos = Unsplash::Photo.search(title, page = 1, per_page = 1)
    self.image = photos.first.urls.regular if photos.any?
  end

  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :blog_posts, dependent: :destroy
  validates :email, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!

end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_blog_post, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /blog_posts
  def index
    @blog_posts = BlogPost.all
  end

  # GET /blog_posts/1
  def show; end

  # GET /blog_posts/new
  def new
    @blog_post = current_user.blog_posts.new
  end

  # GET /blog_posts/1/edit
  def edit; end

  # POST /blog_posts
  def create
    @blog_post = current_user.blog_posts.new(blog_post_params)

    if @blog_post.save
      redirect_to @blog_post, notice: 'Blog post was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /blog_posts/1
  def update
    if @blog_post.update(blog_post_params)
      redirect_to @blog_post, notice: 'Blog post was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /blog_posts/1
  def destroy
    @blog_post.destroy
    redirect_to blog_posts_url, notice: 'Blog post was successfully destroyed.'
  end

  private

  def set_blog_post
    @blog_post = BlogPost.find(params[:id])
  end

  def blog_post_params
    params.require(:blog_post).permit(:title, :content, :image)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/blog_posts/_blog_post.html.erb
<div id="<%= dom_id blog_post %>">
  <p>
    <strong>Title:</strong>
    <%= blog_post.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= blog_post.content %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= image_tag(blog_post.image) if blog_post.image.present? %>
  </p>

</div>

app/views/blog_posts/_form.html.erb
<%= form_with(model: blog_post, local: true, html: { class: "form-horizontal" }) do |form| %>
  <% if blog_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog_post.errors.count, "error") %> prohibited this blog_post from being saved:</h2>
      <ul>
        <% blog_post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title , class: "col-form-label"%>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :content, class: "col-form-label" %>
    <%= form.text_area :content, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit %>
  </div>
<% end %>

app/views/blog_posts/edit.html.erb
<h1 class="text-center">Editing blog post</h1>

<%= render "form", blog_post: @blog_post %>

<br>

<div>
  <%= link_to "Show this blog post", @blog_post %> |
  <%= link_to "Back to blog posts", blog_posts_path %>
</div>

app/views/blog_posts/index.html.erb
<% if user_signed_in? %>
  <h1 class="alert-warning text-center">WELLCOME TO BLOG APP, <%= current_user.email %>!</h1>
  <p style="color: green"><%= notice %></p>
  <h1>Blog Posts</h1>
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Content</th>
        <th>Image</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @blog_posts.each do |blog_post| %>
        <tr id="<%= dom_id(blog_post) %>">
          <td><%= blog_post.title %></td>
          <td><%= truncate(blog_post.content, length: 100) %></td>
          <td style="background-image: url('<%= blog_post.image %>'); background-size: cover; width: 150px; height: 100px;"></td>
          <td class="input-group-text">
            <%= link_to 'Show', blog_post, class: 'btn btn-primary' %> 
            <% if blog_post.user_id == current_user.id %>
              <%= link_to 'Edit', edit_blog_post_path(blog_post), class: 'btn btn-warning' %> 

              <%= button_to 'Destroy', blog_post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
            <% end %>
            
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to 'New Blog Post', new_blog_post_path,class: 'btn btn-primary' %>

<% else %>
  <%= link_to 'Login', new_user_session_path, class: 'btn btn-primary' %>
  <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-secondary' %>
<% end %>

app/views/blog_posts/new.html.erb
<h1 class="text-center">New blog post</h1>

<%= render "form", blog_post: @blog_post %>

<br>

<div>
  <%= link_to "Back to blog posts", blog_posts_path %>
</div>

app/views/blog_posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @blog_post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @blog_post.content %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag(@blog_post.image) if @blog_post.image.present? %>
</p>
<% if @blog_post.user_id == current_user.id %>
<%= link_to 'Edit', edit_blog_post_path(@blog_post),  class: 'btn btn-primary' %> 
<% end %>
<%= link_to 'Back', blog_posts_path,  class: 'btn btn-primary' %>

app/views/homes/index.html.erb
<h1>Welcome to MyApp</h1>
<% if user_signed_in? %>
  <p>Hello, <%= current_user.email %>!</p>
  <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: 'btn btn-primary' %> 
<% else %>
  <%= link_to 'Login', new_user_session_path, class: 'btn btn-primary' %>
  <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-secondary' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyApp</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  <!-- Bootstrap CSS -->
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
  <% if user_signed_in? %>
    <div class="alert-dark input-group-prepend">
      <%= link_to 'Home', root_path,class: 'btn btn-primary' %>
      <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: 'btn btn-danger' %> 
    </div>
  <%end%>

</head>

<body>
  <div class="container mt-5">
    <% flash.each do |key, message| %>
      <div class="alert alert-<%= key == 'notice' ? 'success' : 'danger' %> alert-dismissible fade show" role="alert">
        <%= message %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <%= yield %>
  </div>

  <!-- Bootstrap JS and dependencies -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>